### ISSUE TITLE
shulker box + hopper cause dupe

### ISSUE THREAD

**Issue by cgw2023** [Artillex-Studios/AxShulkers#7]
put item in shulker box, place above a hopper
the first item that appears will be doubled
https://youtu.be/H3l38ScI1mU

**Comment by BenceX100** [comment]
I will fix this ASAP. You are using folia, right?

**Comment by cgw2023** [comment]
yes

**Comment by BenceX100** [comment]
Okay, so what I have found is that this only works on folia servers, because for some reason on bukkit it takes 1 tick before a hopper tries to take items from shulkers, but on folia (and also in vanilla) it is instant.

I will have to recode the shulker placement part, I will try to do this within a few hours

**Comment by BenceX100** [comment]
Try the [latest version](https://github.com/Artillex-Studios/AxShulkers/releases/tag/1.4.5)
